### ISSUE TITLE
compile to bourne shell (sh) instead of bash

### ISSUE THREAD

**Issue by ptman** [batsh-dev-team/Batsh#14]
Bash is _not_ available everywhere. POSIX mandates bourne shell compatibility. So please target that instead.

**Comment by dumblob** [comment]
What's the status of this? Bash is really by far not available everywhere. E.g. `local` is not POSIX and it doesn't seem to be added to POSIX any time soon. There are also lots of other incompatibilities among BSD `sh`ells and Bash etc.

**Comment by theAkito** [comment]
> 
> 
> What's the status of this? Bash is really by far not available everywhere. E.g. `local` is not POSIX and it doesn't seem to be added to POSIX any time soon. There are also lots of other incompatibilities among BSD `sh`ells and Bash etc.

As you more or less invertedly implied in [your other comment](https://github.com/batsh-dev-team/Batsh/issues/26#issuecomment-602695503), you can install and use `bash`, anywhere. That said, can you give us an example of a use case where there is a compilation to POSIX `sh` _needed_?
The reasons I ask is, that I am certain, that there is a tiny amount of actual use cases where you actually need a strict POSIX shell, like e.g. on BSD systems. Why do you think it is smart to adjust the whole compilation process for EVERY USER, just because of some tiny exceptions? Especially, since `bash` is by far plain better than `sh`.

I would rather recommend BSD to use `bash` instead of trying to change a valid project with a valid system, like e.g. the compilation to bash.

**Comment by dumblob** [comment]
>As you more or less invertedly implied in your other comment, you can install and use `bash`, anywhere.

Don't know what you mean. It's exactly the opposite of what you're saying - the whole point of this project is to **not** require anything to get installed but use just what's **always** on the system. But maybe I'm missing something.

On Windows you get Visual Basic and batch (cmd.exe). On unix (incl. macOS and Linux) you get **POSIX** `sh` (i.e. not bash).

>I would rather recommend BSD to use bash instead of trying to change a valid project with a valid system, like e.g. the compilation to bash.

You can't install anything - that's the whole point someone would want to use this project. On Windows I could also download and install in seconds the well maintained [Git for Windows](https://git-scm.com/download/win ) to get a POSIX `sh` (it's actually `bash` because of some apps in the package requiring bashisms :wink:) and enjoy the "write once, run everywhere" (I did it several times and it was a breeze).

But it's simply not always possible to install anything, so one needs to use the common denominator which is why I came across this project.

**Comment by theAkito** [comment]
@dumblob 

> You can't install anything

I think this isn't the default, because the last time I used a BSD based system, I could very well install packages.




> But it's simply not always possible to install anything

That's correct. However, how often do you encounter such a scenario?
Or even better:
How often do you encounter a read-only system, that at the same time needs BATSH to work better?

**Comment by dumblob** [comment]
>>You can't install anything
>
>I think this isn't the default, because the last time I used a BSD based system, I could very well install packages.

It's not a default anywhere (not even on any Windows system). We're talking about company/office/enterprise/university/server/... deployments with strict rules (policies) what can and can not be done.

If you could install system-wide packages/whatever, then you basically had root access. I.e. a scenario which doesn't apply at all here.

>That's correct. However, how often do you encounter such a scenario?
>Or even better:
>How often do you encounter a read-only system, that at the same time needs BATSH to work better?

About as often as I need something like "Batsh". Especially with the prevalence of macOS (i.e. BSD) and Windows systems with limited policies (at places listed above), this pops up every now and then.

**Comment by theAkito** [comment]
> then you basically had root access. I.e. a scenario which doesn't apply at all here.



> About as often as I need something like "Batsh". Especially with the prevalence of macOS (i.e. BSD) and Windows systems with limited policies (at places listed above), this pops up every now and then.

Okay, can you give me a real life example, where you need to do the same thing for Windows and ~~ba~~sh by using batsh? I think the example you display is not only extremely rare (apparently our experience differs on that matter) but also not really a batsh use case. What do you need to script for a restricted system like that? I am curious, because I can't really think of an actual real life example script.

**Comment by dumblob** [comment]
>Okay, can you give me a real life example, where you need to do the same thing for Windows and bash by using batsh?

Roaming among different PCs (Windows, macOS) with data & apps on your flash drive.

>I think the example you display is ... also not really a batsh use case.

This caught my eye. What's the primary motivation (use case) for *batsh* then?

>What do you need to script for a restricted system like that? I am curious, because I can't really think of an actual real life example script.

On-site technical workers working as customer support or deployment specialists are the most common people around me, who are in an utter need for this. The systems they're repairing/deploying/testing/... are always hybrid (Windows, *nix systems including macOS) because of their size and span. These workers roam a lot (both physically and virtually through e.g. TeamViewer remote desktops) and many are every second day on a different place - often hundreds and thousands of kilometers away from the place before.

It's a nightmare to prepare software for these guys because of cross-system (in)compatibility.
